### ISSUE TITLE
MD5 is reported unsafed

### ISSUE THREAD

**Issue by ysdyaoguai** [michaelschwarz/Ajax.NET-Professional#12]
As title said, I think md5 is not a safe way to encrypt.
Then we use sha256 instead.

return BitConverter.ToString(new SHA256Managed().ComputeHash(data)).Replace("-", String.Empty);

**Comment by michaelschwarz** [comment]
Hi @ysdyaoguai,

as the data is not a user input and there is no security behind we assume this is not a security issue. The hash itself is only used to compare different content that is generated by the library itself.

However, we will review this and possibly change that. Thanks for reporting!

Regards, Michael
