### ISSUE TITLE
Google Chrome Issue with doStateChange in core.ashx

### ISSUE THREAD

**Issue by JavaScriptDude** [michaelschwarz/Ajax.NET-Professional#13]
Google Chrome cannot be depended upon to send a `xhr.statusText` of `"OK"` when `xhr.status == 200`. 

This results in intermittent false fails in Chrome browser.

I suggest removing the check for `"OK"` in the line `if(this.xmlHttp.status == 200 && this.xmlHttp.statusText == "OK") {` and instead just use the `xhr.status`.

Info:

- https://github.com/axios/axios/issues/1501
- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/statusText

**Comment by michaelschwarz** [comment]
Hi @JavaScriptDude,

thanks a lot for your feedback, and I will add this shortly after having some tests done. But I agree that status should be enough here.
