### ISSUE TITLE
Compiled regex making GetIJavaScriptObjectFromXmlNode slower

### ISSUE THREAD

**Issue by alivirya** [michaelschwarz/Ajax.NET-Professional#14]
We've recently updated the library from `6.7.20.1` to `21.12.22.1` due to the security vulnerabilities and have found the library to run considerably slower after the upgrade. We've narrowed down the change to this commit: https://github.com/michaelschwarz/Ajax.NET-Professional/commit/cded0136f2bb685716903c6ec180e94e0dc85b87#diff-11180be976ef7ec[…]df0a3ac2ffef214b9R344
and this line specifically: https://github.com/michaelschwarz/Ajax.NET-Professional/blob/08ca42ef66dc70c9aa9f276dfc7cff78bdb9bbdf/AjaxPro/JSON/JavaScriptUtil.cs#L398

It looks like adding the option `System.Text.RegularExpressions.RegexOptions.Compiled` has made it slower as the regex needs to be initialized everytime the function is called. As the function is recursive for each xml node, manual testing has shown our ajax calls go considerably slower, with the size of the data increasing the time for the ajax requests to load

Loading a dataset of ~100 goes from from <100ms to ~500ms
Loading a dataset of ~1000 goes from <200ms to ~7seconds

As a fix, making the regex a private static variable with the compiled option seems to reduce the time back to normal or it could be reverted back to what it was before without the compiled option.

Had a quick look elsewhere in the library where regexes are referenced too and it looks like its generally declared as a private variable in the class instead of within a function (https://github.com/michaelschwarz/Ajax.NET-Professional/blob/f845e338904de7db69086[…]7a2d33840b1dd8b62b/AjaxPro/JSON/Converters/DateTimeConverter.cs) so creating a private static variable for it would be consistent with other places where regexes are used

**Comment by michaelschwarz** [comment]
Hi @[alivirya](https://github.com/alivirya),

thanks a lot for your feedback here, I didn't noticed this performance issue.

I will added this to the next release.
