### ISSUE TITLE
can supply a compressed version for all the js file?

### ISSUE THREAD

**Issue by sxwailyc** [michaelschwarz/Ajax.NET-Professional#17]
can supply a compressed version for all the js file?

**Comment by michaelschwarz** [comment]
Hi @sxwailyc,

yes, you can use web.config to specify your own compress files. In addition, on IIS you can set dynamic created files to be compressed as well.

Please let me know if you need any further help here!

Regards,
Michael

**Comment by michaelschwarz** [comment]
Hi @sxwailyc

I did not receive any feedback. Is this issue still open?

**Comment by sxwailyc** [comment]
@michaelschwarz tks
