### ISSUE TITLE
Latest v23.5.10.1 DLL net20 is actually in .Net framework v4.8

### ISSUE THREAD

**Issue by Awhesian** [michaelschwarz/Ajax.NET-Professional#19]
Hi, the latest release DLL that has net20 and net48 are both same framework.

This is the same case via NuGet.

I had to downgrade to AjaxNetProfessional.22.3.20.1 as thats the latest version with the correct .Net framework.

Cheers.

**Comment by michaelschwarz** [comment]
Hi @Awhesian,

are you still using .NET Framework 2? We discussed earlier to not support it anymore. If there is a need we will revert and offer both libraries.

**Comment by Awhesian** [comment]
Thanks for your response! I noticed the latest release includes both net20 and net48 DLLs. If support for net20 has been dropped, could you clarify why it’s still being included?

**Comment by michaelschwarz** [comment]
Ok, will fix this. This seems to be a mistake when building.

**Comment by Awhesian** [comment]
ah okay, thanks again for clarifying

**Comment by michaelschwarz** [comment]
Version 24.10.10.1 is available on NuGet.
