### ISSUE TITLE
some problems about Content Security Policy Header

### ISSUE THREAD

**Issue by Chain-Yu** [michaelschwarz/Ajax.NET-Professional#5]
Ajaxpro is used in my project, which will eventually generate some JavaScript code on the web page. Now I need to handle the inline JavaScript code with "content security policy header"

My purpose is as follows:

Before:

<script>

function fun(){

    // some code generated by ajaxPro

}

</script>

After:

<script nonce='abcdefghijklmnopqrstuvwxyz'>

function fun(){

    // some code generated by ajaxPro

}

</script>
-----------------------------------------------------------

I added the following configuration in the web.config file

&lt;httpProtocol&gt;

&lt;customHeaders&gt;

&lt;add name ="Content-Security-Policy" value ="frame-ancestors myhost.com; script-src 'self' https://myhost.com 'unsafe-eval' 'unsafe-hashes' 'nonce-abcdefghijklmnopqrstuvwxyz';" /&gt;

&lt;/customHeaders&gt;

&lt;/httpProtocol&gt;

------------------------------------------------------------

My question is: how can I add 'nonce' to the < script > tag generated by ajaxpro?

If you need more information, you can email me: 3251362399@qq.com

**Comment by michaelschwarz** [comment]
Hi Chain-Yu,

in which .NET Framework version are you using the library?

**Comment by michaelschwarz** [comment]
Please give it a try, take the latest source that accept a `<contentSecurityPolicy nonce="abcdefghijklmnopqrstuvwxyz" />` configuration in web.config for your nonce value.

**Comment by Chain-Yu** [comment]
hi, i have taken the latest source and build its 'Release'
now i should add&nbsp;&nbsp;<contentSecurityPolicy nonce="abcdefghijklmnopqrstuvwxyz" /&gt;&nbsp; configuration in which node in Web.Config?
<system.web&gt;&nbsp; or&nbsp; <system.webServer&gt;&nbsp; or any other node?




Best Regards


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "michaelschwarz/Ajax.NET-Professional"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [michaelschwarz/Ajax.NET-Professional] some problems about Content Security Policy Header (Issue #5)





 
Please give it a try, take the latest source that accept a <contentSecurityPolicy nonce="abcdefghijklmnopqrstuvwxyz" /&gt; configuration in web.config for your nonce value.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chain-Yu** [comment]
hi Mr.Schwarz， I have checked your latest commit, it works very well !!!  thanks for your fix ~
